version: '3'

services:
  db:
    container_name: db
    image: postgres:13-alpine
    ports:
      - 15432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./doc/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: db
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always

  app:
    container_name: app
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./src:/app/src
    environment:
      DATABASE_URL: postgres://postgres@db:5432/db
    depends_on:
      - db
    restart: always

volumes:
  db:
