openapi: 3.1.0
info:
  title: hello-server
  version: 0.1.0
  description: API サーバ実装のスケルトン
  contact:
    name: Kazuki Awasawa
servers:
  - url: 'http://localhost:8080/api'
paths:
  /version:
    get:
      summary: バージョン情報取得
      operationId: get-users-userId
      description: バージョン情報を取得します。
      responses:
        '200':
          description: 正常に処理されました。
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: 正常に処理されたかどうかを示す値
                  name:
                    type: string
                    description: API サーバ名
                  version:
                    type: string
                    description: API バージョン
                  isProd:
                    type: boolean
                    description: Production バージョンであるかどうかを示す値
      tags:
        - util
  /auth/signup:
    post:
      summary: サインアップ
      tags:
        - auth
      responses:
        '200':
          description: 正常に処理されました。
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: 正常に処理されたかどうかを示す値
        '400':
          description: リクエストパラメータに不備があります。
        '409':
          description: 登録済みのメールアドレスです。
      operationId: post-auth-signup
      description: サインアップします。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  maxLength: 255
                  example: user name
                  description: ユーザ名
                email:
                  type: string
                  maxLength: 255
                  format: email
                  description: メールアドレス
                password:
                  type: string
                  format: password
                  maxLength: 255
                  description: パスワード
              required:
                - name
                - email
                - password
  /auth/signin:
    post:
      summary: サインイン
      tags:
        - auth
      responses:
        '200':
          description: 正常に処理されました。
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: 正常に処理されたかどうかを示す値
                  token:
                    type: string
                    description: アクセストークン
                  '':
                    $ref: '#/components/schemas/User'
        '400':
          description: リクエストパラメータに不備があります。
        '401':
          description: 認証情報に不備があります。
      operationId: post-auth-signin
      description: サインインします。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: メールアドレス
                password:
                  type: string
                  description: パスワード
              required:
                - email
                - password
  /auth/signout:
    post:
      summary: サインアウト
      operationId: post-auth-signout
      responses:
        '200':
          description: 正常に処理されました。
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: 正常に処理されたかどうかを示す値
        '400':
          description: リクエストヘッダーに不備があります。
        '401':
          description: アクセストークンに不備があります。
      tags:
        - auth
      description: サインアウトします。
      parameters:
        - schema:
            type: string
          in: header
          name: x-access-token
          description: アクセストークン
          required: true
  /auth/withdraw:
    delete:
      summary: 退会
      operationId: delete-auth-withdraw
      responses:
        '200':
          description: 正常に処理されました。
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: 正常に処理されたかどうかを示す値
        '400':
          description: リクエストヘッダー、またはリクエストパラメータに不備があります。
        '401':
          description: 認証情報に不備があります。
        '404':
          description: ユーザ情報を取得できませんでした。
      description: 退会します。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  description: パスワード
              required:
                - password
      parameters:
        - schema:
            type: string
          in: header
          name: x-access-token
          description: アクセストークン
          required: true
      tags:
        - auth
  /auth/identify:
    post:
      summary: 本人確認メール送信
      tags:
        - auth
      responses:
        '200':
          description: 正常に処理されました。
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: 正常に処理されたかどうかを示す値
        '400':
          description: リクエストヘッダーに不備があります。
        '401':
          description: 認証情報に不備があります。
        '403':
          description: このメールアドレスは認証済みです。
      operationId: post-auth-identify
      description: 本人確認メールを送信します。
      parameters:
        - schema:
            type: string
          in: header
          name: x-access-token
          description: アクセストークン
          required: true
  '/auth/verify/identify/{id}/{hash}':
    get:
      summary: 本人確認メール検証
      tags:
        - auth
      responses:
        '201':
          description: 正常に処理されました。
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: 正常に処理されたかどうかを示す値
                  message:
                    type: string
                    description: メッセージ
        '204':
          description: このメールアドレスは認証済みです。
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: 正常に処理されたかどうかを示す値
                  message:
                    type: string
                    description: メッセージ
        '401':
          description: リクエストパラメータに不備があります。
      operationId: get-verify-identify
      x-internal: true
      description: 本人確認メールを検証します。
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ユーザID
      - schema:
          type: string
        name: hash
        in: path
        required: true
        description: ハッシュ値
  /auth/reset-password:
    post:
      summary: パスワード再設定リンク送信
      operationId: post-auth-reset-password
      responses:
        '200':
          description: 正常に処理されました。
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: 正常に処理されたかどうかを示す値
        '400':
          description: リクエストパラメータに不備があります。
        '401':
          description: メールアドレスに不備があります。
      tags:
        - auth
      description: パスワード再設定リンクを送信します。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: メールアドレス
              required:
                - email
  '/auth/reset-password/{token}':
    parameters:
      - schema:
          type: string
        name: token
        in: path
        required: true
        description: パスワードリセットトークン
    get:
      summary: パスワード再設定フォーム表示
      tags:
        - auth
      responses:
        '200':
          description: 正常に処理されました。
        '401':
          description: メールアドレス、またはパスワードリセットトークンに不備があります。
      operationId: get-auth-reset-password-token
      x-internal: true
      parameters:
        - schema:
            type: string
          in: query
          name: email
          description: メールアドレス
          required: true
      description: パスワード再設定フォームを表示します。
  /auth/verify/reset-password:
    post:
      summary: パスワード再設定
      tags:
        - auth
      responses:
        '200':
          description: 正常に処理されました。
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: 正常に処理されたかどうかを示す値
        '400':
          description: リクエストパラメータに不備があります。
        '401':
          description: メールアドレス、またはパスワードリセットトークンに不備があります。
      operationId: post-auth-verify-reset-password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: パスワードリセットトークン
                email:
                  type: string
                  format: email
                  maxLength: 255
                  description: メールアドレス
                password:
                  type: string
                  format: password
                  maxLength: 255
                  description: パスワード
                passwordConfirmation:
                  type: string
                  description: パスワード（確認用）
                  format: password
                  maxLength: 255
              required:
                - token
                - email
                - password
                - passwordConfirmation
        description: ''
      description: パスワードを再設定します。
      x-internal: true
  /auth/refresh:
    get:
      summary: 認証トークン再生成
      tags:
        - auth
      responses:
        '200':
          description: 正常に処理されました。
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: 正常に処理されたかどうかを示す値
                  token:
                    type: string
                    description: アクセストークン
        '401':
          description: リフレッシュトークンに不備があります。
      operationId: get-auth-refresh
      description: 認証トークンを再生成します。
      parameters:
        - schema:
            type: string
          in: cookie
          name: token
          description: リフレッシュトークン
          required: true
  /user:
    get:
      summary: ユーザ情報取得
      tags:
        - users
      responses:
        '200':
          description: 正常に処理されました。
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: 正常に処理されたかどうかを示す値
                  user:
                    $ref: '#/components/schemas/User'
        '404':
          description: ユーザ情報を取得できませんでした。
      operationId: get-user
      description: ユーザ情報を取得します。
      parameters:
        - schema:
            type: string
          in: header
          name: x-access-token
          description: アクセストークン
          required: true
    patch:
      summary: ユーザ情報更新
      operationId: patch-user
      responses:
        '200':
          description: 正常に処理されました。
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: 正常に処理されたかどうかを示す値
                  user:
                    $ref: '#/components/schemas/User'
        '400':
          description: リクエストパラメータに不備があります。
        '404':
          description: ユーザ情報を取得できませんでした。
      tags:
        - users
      description: ユーザ情報を更新します。
      parameters:
        - schema:
            type: string
          in: header
          name: x-access-token
          description: アクセストークン
          required: true
components:
  schemas:
    User:
      title: User
      type: object
      description: ユーザモデル
      properties:
        name:
          type: string
          description: ユーザ名
          maxLength: 255
          example: user name
        email:
          type: string
          format: email
          description: メールアドレス
          maxLength: 255
        verified:
          type: boolean
          description: メールアドレスが認証されているかどうかを示す値
      required:
        - name
        - email
        - verified
  securitySchemes: {}
tags:
  - name: auth
  - name: users
  - name: util
